apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: producteur
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: alpine
        image: alpine:3.12
        command: ["/bin/sh", "-c"]
        args: ["while sleep 60; do echo $HOSTNAME $(date) > /var/html/index.html; done"]  
        volumeMounts:
          - name: html
            mountPath: /var/html/
      volumes:
      - name: html
        hostPath: 
          path: /tmp
