apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: producteur
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: alpine
        image: alpine:3.12
        command: ["/bin/sh", "-c"]
        args: ["while sleep 60; do echo $HOSTNAME $(date) > /web/index.html; done"]  
        volumeMounts:
          - name: web
            mountPath: /web
      volumes:
      - name: web
        hostPath:
          path: /
