apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name : httpd
        image: httpd
        volumeMounts:
          - name: web
            mountPath: /htdocs
      volumes:
      - name: web
        hostPath:
          path: /
